### ISSUE TITLE
Plugin fails when remote jenkins can not be reached

### ISSUE THREAD

**Issue by rsimiciuc** [morficus/Parameterized-Remote-Trigger-Plugin#4]
https://github.com/morficus/Parameterized-Remote-Trigger-Plugin/blob/master/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L535

Null pointer exception here since queryResponseObject is null.

**Comment by morficus** [comment]
this should have been fixed with this commit: https://github.com/morficus/Parameterized-Remote-Trigger-Plugin/commit/a9dda51bf9db876017402ce91bc4b70e0ee08ec6

**Comment by atom-b** [comment]
This is still an issue though not because of line 535. I have a build that fails due to a null reference exception in  [isRemoteJobParameterized()](https://github.com/morficus/Parameterized-Remote-Trigger-Plugin/blob/master/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L1167) when the remote Jenkins is unreachable. 

Relevant portion of the build log:

```
[ other remotes are triggered successfully... ]

connect timed out
Connection to remote server failed, waiting for to retry - 10 seconds until next attempt.
Retry attempt #1 out of 5
connect timed out
Connection to remote server failed, waiting for to retry - 10 seconds until next attempt.
Retry attempt #2 out of 5
connect timed out
Connection to remote server failed, waiting for to retry - 10 seconds until next attempt.
Retry attempt #3 out of 5
connect timed out
Connection to remote server failed, waiting for to retry - 10 seconds until next attempt.
Retry attempt #4 out of 5
connect timed out
Connection to remote server failed, waiting for to retry - 10 seconds until next attempt.
Retry attempt #5 out of 5
connect timed out
ERROR: Remote build failed for the following reason, but the build will continue:
ERROR: Max number of connection retries have been exeeded.
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.isRemoteJobParameterized(RemoteBuildConfiguration.java:1167)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.perform(RemoteBuildConfiguration.java:488)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Trigger a remote parameterized job' marked build as failure
Finished: FAILURE
```
